port: 4000
host: 127.0.0.1

url: https://katydecorah.com
permalink: /:categories/:title/
author:
  name: Katy DeCorah
  email: katydecorah@gmail.com
  uri: https://katydecorah.com
assets: //yo.katydecorah.com/

repository: katydecorah/katydecorah.github.io

paginate: 5
paginate_path: ":num"
future: true

title: Katy DeCorah
description: "Frontend engineer and tinkerer from Saratoga Springs, NY."
image: //yo.katydecorah.com/katy-decorah@1600.jpg
twitter: "@katydecorah"

collections:
  favorites:
    output: true

# for adventures.geojson + year review pages
years:
  - 2020
  - 2019
  - 2018
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013
  - 2012
  - 2011
  - 2010
  - 2009
  - 2008
  - 2005

sass:
  style: :compressed

timezone: America/New_York

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-mentions

feed:
  categories:
    - code

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  footnote_backlink_inline: true

exclude:
  - vendor
  - CNAME
  - README.md
  - node_modules
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - test
  - img/posts
  - packages
  - katydecorah.dic

links:
  - text: CodePen
    url: https://codepen.io/katydecorah/
    icon: codepen
    position: bottom
  - text: Github
    url: https://github.com/katydecorah
    icon: github
    position: bottom
  - text: Twitter
    url: https://twitter.com/katydecorah
    icon: twitter
    position: bottom
  - text: Instagram
    url: https://instagram.com/katydecorah
    icon: instagram
    position: bottom
  - text: Email
    url: mailto:&#107;&#097;&#116;&#121;&#100;&#101;&#099;&#111;&#114;&#097;&#104;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;
    icon: mail
    position: bottom
  - text: RSS
    url: /feed.xml
    icon: rss
    position: bottom

mapbox-token: pk.eyJ1Ijoia2F0eWRlY29yYWgiLCJhIjoiY2l0YzVhY2l6MGE0eDJ6czZ2NDRpZGtubyJ9.njBRjO2lRXdT0Mut9Vryqg
mapid: katydecorah.21d6ba77
mapid-winter: katydecorah.70f1a6d1
mapboxjs: v3.0.1
leafletjs: v1.0.0
jquery: 3.1.1
modernizr: 2.8.3

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "favorites"
    values:
      layout: "default"
