port: 4000
host: 127.0.0.1

url: http://katydecorah.com
permalink: /:categories/:title/
author:
  name: Katy DeCorah
  email: katydecorah@gmail.com
  uri: http://katydecorah.com

paginate: 5
paginate_path: ":num"
future: true

name: Katy DeCorah
description: "Front-end developer and tinkerer from Saratoga Springs, NY."
image: https://c1.staticflickr.com/9/8881/18361278301_f8ac7d25d4_h.jpg
twitter: "@katydecorah"

# for adventures.geojson + year review pages
years:
- 2016
- 2015
- 2014
- 2013
- 2012
- 2011
- 2010
- 2009
- 2008
- 2005

sass:
  style: :compressed

timezone: America/New_York

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
  - vendor
  - CNAME
  - README.md
  - node_modules
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - package.json
  - test

links:
- text: Hello!
  url: /hello/
  position: top
- text: Card catalog
  url: /card-catalog/
  position: top
- text: Time capsule
  url: /time-capsule/
  icon: archive
  position: top

- text: CodePen
  url: http://codepen.io/katydecorah/
  icon: codepen
  position: bottom
- text: Github
  url: https://github.com/katydecorah
  icon: github
  position: bottom
- text: Twitter
  url: https://twitter.com/katydecorah
  icon: twitter
  position: bottom
- text: Instagram
  url: http://instagram.com/katydecorah
  icon: instagram
  position: bottom
- text: Feed
  url: /feed.xml
  icon: rss
  position: bottom

mapbox-token: pk.eyJ1Ijoia2F0eWRlY29yYWgiLCJhIjoiY2l0YzVhY2l6MGE0eDJ6czZ2NDRpZGtubyJ9.njBRjO2lRXdT0Mut9Vryqg
mapid: katydecorah.21d6ba77
mapid-winter: katydecorah.70f1a6d1
mapboxjs: v3.0.1
leafletjs: v1.0.0
jquery: 3.1.1
modernizr: 2.8.3

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
